apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.repository}} 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.envFrom.configMapRef.name }}
            - secretRef:
                name: {{ .Values.envFrom.secretRef.name }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
